apiVersion: v2
name: jambonz
version: 10.0.0
appVersion: 10.0.3
description: jambonz CPaaS for communication service providers
home: https://jambonz.org
keywords:
  - voip
  - cpaas
  - webRTC
  - sip
  - rtp
maintainers:
  - name: Dave Horton
    email: daveh@drachtio.org