{{- if .Values.sbc.sip.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: drachtio-secret
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "sip TLS certificate" .Values.sbc.sip.ssl.crt | b64enc | quote }}
  tls.key: {{ required "sip TLS private key" .Values.sbc.sip.ssl.key | b64enc | quote }}
{{- end }}