apiVersion: v1
kind: Secret
metadata:
  name: jambonz-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
    # use 32 bytes of random value, hex
    MYSQL_PASSWORD: {{ .Values.mysql.secret }}
    {{- if .Values.mysql.rootSecret }}
    MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootSecret}}
    {{- end }}
    DRACHTIO_SECRET: {{ .Values.drachtio.secret }}
    JWT_SECRET: {{ .Values.jwt.secret }}
    # use 32 bytes of random value, hex
    POSTGRES_PASSWORD: {{ .Values.postgres.secret }}

