{{- if .Values.global.logging.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
{{ include "common.labels" . | indent 4 }}
  name: loki
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: loki
  clusterIP: None
{{- end }}
