{{- if .Values.global.logging.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: loki
{{ include "common.labels" . | indent 4 }}
  name: loki
  namespace: {{ .Release.Namespace | quote }}
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      name: loki
      labels:
        app: loki
      annotations:
        {{- if .Values.global.podAnnotations }}
        {{ toYaml .Values.global.podAnnotations | default "" | nindent 8 }}
        {{- end }}
        {{- if .Values.loki.podAnnotations }}
        {{ toYaml .Values.loki.podAnnotations | default "" | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      {{- if .Values.affinity }}
      affinity:
        {{ toYaml .Values.affinity | default "" | nindent 8 }}
      {{- end }}
      containers:
        - name: loki
          image: {{ .Values.loki.image }}
          args:
            - -config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
              name: http
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources: {}
          volumeMounts:
            - name: loki-data
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki/loki.yaml
              subPath: loki.yaml
      restartPolicy: Always
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
  volumeClaimTemplates:
    - metadata:
        name: loki-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.storageClassName }}
        storageClassName: {{ .Values.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.loki.storage }}
{{- end }}
